apiVersion: v1
kind: ServiceAccount
metadata:
  name: rag-engine-worker
  namespace: rag-engine
  annotations:
    iam.gke.io/gcp-service-account: "rag-prod-app-sa@your-project-id.iam.gserviceaccount.com"
